version: "3.9"
services:
  web:
    build: .
    command: gunicorn core.wsgi -b 0.0.0.0:8000 --timeout 90
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # python3 -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'
      - "DJANGO_SECRET_KEY=50characterstring!"
      # [::1] is the loopback address in ipv6, the equivalent would be 127.0.0.1 in ipv4.
      - "DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "CSRF_TRUSTED_ORIGINS=http://site.com,https://site.com"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: