version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - db
    labels:
      - "traefik.enable=true" # enables Traefik to discover the service
      - "traefik.http.routers.django.rule=Host(`django.localhost`)"
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-z4nyx@wkok1(98%kl5^!$m_316z)_d-h2yd6@zxgzten7@z4wf"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
  traefik: # new
    image: traefik:v2.9.6
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      # maps the local config file to the config file in the container so that the settings are kept in sync
      - "$PWD/traefik.dev.toml:/etc/traefik/traefik.toml"
      # enables Traefik to discover other containers
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
